### ISSUE TITLE
CNC drill file

### ISSUE THREAD

**Issue by Synthesizer-repair** [adwuard/dirtywave-m8-headless-keyboard#2]
Noticed that the CNC does not include the drill file.  It would be great to have that file included in the hardware sources, so that the holes needed can be drilled and properly tapped with threads using MFG services.

**Comment by adwuard** [comment]
Thanks for the input!
I am not quite familiar with the CAM drill file, and how it can be generated with Fusion360. Usually, I would just need to point out where to tap and my local CNC services does it. 

In terms of drill file maybe a little more info and direction on what kind of files is needed. I might be able to figure it out on how to generate with Fusion 360.
Or, I could generate 2D PDFs indicate drill and thread size.

**Comment by DOSputin** [comment]
If we're going to the trouble of a PCB & enclosure redesign, why not also include analog audio I/O on 3.5mm also?
Using a shield PCB with all these I/O, midi & audio, works with headless m8.  ie: https://codeberg.org/dcoredump/TeensyMIDIAudio/src/branch/master/T4.1-Adapter-Board_Rev-1.0

Seems like it would be worth the efforts?

**Comment by adwuard** [comment]
@Synthesizer-repair I see, CAM and G-code I do familiar. But G-code and tool paths this usually generated by the CNC fab house. Since the tools, and machines are different. Some more qualified CNC fab house even have auto tool change for tapping. Some do it at post manually. For automated tool change or tapping This requires custom G-code commands and database of their tool-sets. And not all fab house have same tooling and capabilities. It's impossible to generate on G-Code/Drill file to fit all.
What I can do with my local CNC shop is to provide 3D STEP and 2D CAD notes for the parts. And fab house decides how to do their tool paths and how they want to tap the holes.

**Comment by adwuard** [comment]
@DOSputin I've heard that Dirtywave removed their MIDI support with their M8 headless firmware. I'm not sure if the MIDI would still work.

**Comment by DOSputin** [comment]
> @DOSputin I've heard that Dirtywave removed their MIDI support with their M8 headless firmware. I'm not sure if the MIDI would still work.

Umm, you heard?   
It works.  There is nothing preventing, you simply have to connect the proper hardware. 
Install headless firmware on an official M8 massively overpriced hardware, the MIDI I/O works.  It's on pins 1 & 28...

**Comment by adwuard** [comment]
@DOSputin  Here more information on the MIDI being removed in headless version that greater than V2.0.

Source: Youtube 
https://www.youtube.com/watch?v=BEqFc5MtHGY
![image](https://github.com/user-attachments/assets/2fc19f2d-c97e-4bf6-8756-7aafa0d843e2)



Source: Discord User Group
![image](https://github.com/user-attachments/assets/8147e160-5790-4587-a3d8-2f4c130135d7)
